FROM hbpmip/airflow-test-py34:1.8.2-0

COPY tests/data/ /src/tests/data/
COPY requirements-dev.txt README.rst setup.cfg setup.py /src/
RUN pip install -r /src/requirements-dev.txt

COPY data_tracking/ /src/data_tracking/
RUN pip install -e /src/

COPY tests/unit_test.py /src/tests/

WORKDIR /src/tests/

ENTRYPOINT ["/bin/sh", "-c", "nosetests", "unit_test.py"]
