"""increase length of several varchar fields

Revision ID: ef2767c69967
Revises: 9d012baee689
Create Date: 2016-06-02 11:00:55.027731

"""

# revision identifiers, used by Alembic.
revision = 'ef2767c69967'
down_revision = '9d012baee689'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequence_type', 'institution_name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('sequence_type', 'manufacturer',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('sequence_type', 'manufacturer_model_name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('sequence_type', 'name',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequence_type', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('sequence_type', 'manufacturer_model_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('sequence_type', 'manufacturer',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.alter_column('sequence_type', 'institution_name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    ### end Alembic commands ###
