"""some fields should be nullable

Revision ID: 1b898eac4efd
Revises: b2a36c103d9e
Create Date: 2016-12-23 10:44:21.753897

"""

# revision identifiers, used by Alembic.
revision = '1b898eac4efd'
down_revision = 'b2a36c103d9e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('participant', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sequence_type', 'columns',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sequence_type', 'echo_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sequence_type', 'echo_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'echo_train_length',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sequence_type', 'flip_angle',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'magnetic_field_strength',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'number_of_phase_encoding_steps',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sequence_type', 'percent_phase_field_of_view',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'percent_sampling',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'pixel_bandwidth',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sequence_type', 'pixel_spacing_0',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'pixel_spacing_1',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'repetition_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'rows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sequence_type', 'slice_thickness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sequence_type', 'space_between_slices',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sequence_type', 'space_between_slices',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'slice_thickness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'rows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sequence_type', 'repetition_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'pixel_spacing_1',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'pixel_spacing_0',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'pixel_bandwidth',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sequence_type', 'percent_sampling',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'percent_phase_field_of_view',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'number_of_phase_encoding_steps',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sequence_type', 'magnetic_field_strength',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'flip_angle',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'echo_train_length',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sequence_type', 'echo_time',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sequence_type', 'echo_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sequence_type', 'columns',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('participant', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    ### end Alembic commands ###
