"""update Processing step and Provenance

Revision ID: 573f9ca528eb
Revises: 9a6fc5dc19c5
Create Date: 2017-01-12 12:41:48.482875

"""

# revision identifiers, used by Alembic.
revision = '573f9ca528eb'
down_revision = '9a6fc5dc19c5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processing_step', sa.Column('execution_date', sa.Date(), nullable=True))
    op.add_column('processing_step', sa.Column('provenance_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_processing_step_provenance_id'), 'processing_step', ['provenance_id'], unique=False)
    op.create_foreign_key(None, 'processing_step', 'provenance', ['provenance_id'], ['id'])
    op.drop_index('ix_provenance_airflow_step_id', table_name='provenance')
    op.drop_constraint(u'provenance_airflow_step_id_fkey', 'provenance', type_='foreignkey')
    op.drop_column('provenance', 'airflow_step_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provenance', sa.Column('airflow_step_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'provenance_airflow_step_id_fkey', 'provenance', 'processing_step', ['airflow_step_id'], ['id'])
    op.create_index('ix_provenance_airflow_step_id', 'provenance', ['airflow_step_id'], unique=False)
    op.drop_constraint(None, 'processing_step', type_='foreignkey')
    op.drop_index(op.f('ix_processing_step_provenance_id'), table_name='processing_step')
    op.drop_column('processing_step', 'provenance_id')
    op.drop_column('processing_step', 'execution_date')
    ### end Alembic commands ###
