"""processing step name not unique

Revision ID: c1ca632c3d16
Revises: fd4ef8c748d8
Create Date: 2017-01-19 12:19:30.945903

"""

# revision identifiers, used by Alembic.
revision = 'c1ca632c3d16'
down_revision = 'fd4ef8c748d8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('processing_step_name_key', 'processing_step', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('processing_step_name_key', 'processing_step', ['name'])
    # ### end Alembic commands ###
