"""add missing field in data_file

Revision ID: dc5e2b38cbc8
Revises: f5ef455c42e0
Create Date: 2017-01-11 17:46:52.565071

"""

# revision identifiers, used by Alembic.
revision = 'dc5e2b38cbc8'
down_revision = 'f5ef455c42e0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_file', sa.Column('type', sa.Text(), nullable=False))
    op.alter_column('data_file', 'output_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('data_file', 'result_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_file', 'result_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('data_file', 'output_type',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('data_file', 'type')
    ### end Alembic commands ###
