"""add field age to participant

Revision ID: e0887922f7df
Revises: 18f6d14fe628
Create Date: 2017-01-23 15:53:57.675916

"""

# revision identifiers, used by Alembic.
revision = 'e0887922f7df'
down_revision = '18f6d14fe628'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('age', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participant', 'age')
    # ### end Alembic commands ###
