"""add column 'others' to 'provenance' table

Revision ID: eb399a96888e
Revises: 3e6823ecebda
Create Date: 2017-01-16 09:48:23.915427

"""

# revision identifiers, used by Alembic.
revision = 'eb399a96888e'
down_revision = '3e6823ecebda'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provenance', sa.Column('others', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provenance', 'others')
    ### end Alembic commands ###
