"""add 'is_copy' boolean field to data_file table

Revision ID: fd4ef8c748d8
Revises: eb399a96888e
Create Date: 2017-01-18 11:11:14.206467

"""

# revision identifiers, used by Alembic.
revision = 'fd4ef8c748d8'
down_revision = 'eb399a96888e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_file', sa.Column('is_copy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_file', 'is_copy')
    # ### end Alembic commands ###
