"""session value from int to string

Revision ID: ff9e52d96271
Revises: 1b898eac4efd
Create Date: 2017-01-11 16:47:24.707033

"""

# revision identifiers, used by Alembic.
revision = 'ff9e52d96271'
down_revision = '1b898eac4efd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'value',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'value',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    ### end Alembic commands ###
